### PR TITLE
Add empty postcss.config.js

### LINKED ISSUE #239: No PostCSS config
A fresh install fails today with the postcoss-loader unless I create `node_modules/bootstrap-loader/postcss.config.js` with the contents ```module.exports={};```

### PR DESCRIPTION
**Pull request by killtheliterate**
This seems to resolve #239

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/241)

### CODE REVIEW

**Comment by justin808** [comment]
@killtheliterate @alexfedoseev @robwise What if the user needs to override the values for postcss?

I pushed 2.0.0-beta.20 with this to try out.

**Comment by justin808** [comment]
```
14:19:30 webpack-hmr.1           | ERROR in ./~/css-loader?{"modules":true,"importLoaders":2,"localIdentName":"[name]__[local]__[hash:base64:5]"}!./~/postcss-loader!./~/sass-loader!./~/sass-resources-loader/lib/loader.js?{"resources":["./app/assets/styles/bootstrap/pre-customizations.scss","./app/assets/styles/bootstrap/replicated-values.scss","./app/assets/styles/resources/variables.scss","./app/assets/styles/resources/mixins.scss","./app/assets/styles/resources/media.scss","./app/assets/styles/resources/z-indexes.scss","./app/assets/styles/resources/elements/common.scss","./app/assets/styles/resources/elements/forms.scss","./app/assets/styles/resources/elements/buttons.scss"]}!./app/assets/styles/globals/base.scss
14:19:30 webpack-hmr.1           | Module build failed: Error: No PostCSS Config found in: /Users/justin/shakacode/react-on-rails-pro/todo-app-production/client/app/assets/styles/globals
```

When I create the missing file, per the error message, I get past the postcss message.

**Comment by killtheliterate** [comment]
Yeah, I don't think this will actually address the issue mentioned. I'll do a bit more investigation as well.

I have the exact same issue once I start pulling in `CSS`

**Comment by justin808** [comment]
@killtheliterate can you verify that this obviates the need to create the postcss file next to the webpack config?

**Comment by justin808** [comment]
@killtheliterate or anybody, should we close or merge this?

**Comment by killtheliterate** [comment]
@justin808 sorry, lost a bit of context here, but I don't think that PR should be merged. If I remember right, I resolved this by using a `postcss.config.js` instead of tacking it into my `webpack.config`.

**Comment by web-snake** [comment]
So how do I resolve #239? I'm getting the same error. I'm trying to use this plugin as a plugin to get a basic app working with Bootstrap. My webpack config is copied from the examples. I don't understand what its actually doing. I'm just stuck with a plugin that doesn't work and if you've solved that you haven't explained it in a way I understand

**Comment by killtheliterate** [comment]
@web-snake add a file called `postcss.config.js` to your application root. Think that's what I mean in my last comment.

**Pull request closed without merging**
