### PR TITLE
Minimal changes necessary for Webpack 5 compatibility

### PR DESCRIPTION
**Pull request by Judahmeek**
Same as #400 without the `lib` directory.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/401)

### CODE REVIEW

**Review by justin808 — CHANGES_REQUESTED** [review]
questions below

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/401#-:-MtfmnXJ9xCLD7pdJCZ3:bsqbn5l)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

___
*[src/utils/processStyleLoaders.js, line 66 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/401#-Mtfmi9S45r9WW3HWpwT:-Mtfmi9S45r9WW3HWpwU:b-m7susq) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/utils/processStyleLoaders.js#L66)):*
> ```JavaScript
> 
>     // eslint-disable-next-line no-param-reassign
>     loadersWithSuffix[sassLoaderIndex] = sassLoaderWithSourceMap;
> ```

1. Will this break compat with older webpack?
2. Can you be sure to put in changelog?

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/401)* status: all files reviewed, 1 unresolved discussion (waiting on @justin808)

___
*[src/utils/processStyleLoaders.js, line 66 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/401#-Mtfmi9S45r9WW3HWpwT:-MtiumKc9y7E6_Eq1011:bop285r) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/utils/processStyleLoaders.js#L66)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

1. Will this break compat with older webpack?
2. Can you be sure to put in changelog?
</blockquote></details>

1. No, because sass-loader's latest versions already get their default sourceMap config from the `devtools` configuration.

2. Sure. How exactly do you want me to phrase it? `bootstrap-loader no longer triggers sourceMap for sass-loader`?

**Review by justin808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/401)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

___
*[src/utils/processStyleLoaders.js, line 66 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/401#-Mtfmi9S45r9WW3HWpwT:-Mtj_a1C6UMNk6Mzh3BC:bkquf3i) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/utils/processStyleLoaders.js#L66)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

1. No, because sass-loader's latest versions already get their default sourceMap config from the `devtools` configuration.

2. Sure. How exactly do you want me to phrase it? `bootstrap-loader no longer triggers sourceMap for sass-loader`?
</blockquote></details>

Sure -- I really have zero idea on this one.

**Review by justin808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/401)* status: all files reviewed, 1 unresolved discussion (waiting on @Judahmeek)

___
*[src/utils/processStyleLoaders.js, line 66 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/401#-Mtfmi9S45r9WW3HWpwT:-Mtj_fPN24ZQroQX_iIx:b-2fnnb9) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/utils/processStyleLoaders.js#L66)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Sure -- I really have zero idea on this one.
</blockquote></details>

maybe just a changelog entry!
maybe a major version bump also!

**Comment by justin808** [comment]
Please update the https://github.com/shakacode/bootstrap-loader/blob/master/CHANGELOG.md and I will merge and release.

**Pull request merged**
