### PR TITLE
fixes polyfill require for node < v4.0.0

### PR DESCRIPTION
**Pull request by mdgraser**
Untested.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/72)

### CODE REVIEW

**Comment by justin808** [comment]
@mdgraser This looks sensible. Can you please verify that you tried this with node current as well as node <= 0.12 and less than 4.0.0?

Did you put in some print statements to check the flow of the code?

Thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/72#-:-KD1Ha7I3l8iZqYv5DyE:-1067406635)*

**Comment by mdgraser** [comment]
@justin808 Tested this morning in node v0.12.12, v4.2.1, and v5.9.0. All with babel 6 (that's what's in my project). I put console logs in and it works as intended in those cases. The problem now is just that you guys are require.resolving polyfill from two different versions of babel and throwing an error in the catch. So this never actually makes it through that block for any node version < 4.

**Comment by justin808** [comment]
@mdgraser I just pushed 1.0.10. Please try it out. Thanks. Also, can you double check my commit to fix the lint issues? https://github.com/shakacode/bootstrap-loader/commit/75702b5003579722bab8296c024d27d5d6007bfe

**Comment by mdgraser** [comment]
@justin808 Commit looks good, 1.0.10 works great for me. Thanks!

**Pull request merged**
