### PR TITLE
Make it up with sass-resources-loader

### PR DESCRIPTION
**Pull request by x-yuri**
Fixes an issue discovered by author in #285 after upgrading `boostrap-loader`.

This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/357)

### CODE REVIEW

**Comment by justin808** [comment]
Can you add an example to https://github.com/shakacode/bootstrap-loader/tree/master/examples?

I'll merge this once I have a small sample where I can verify this.

Also, please confirm that the all the examples, https://github.com/shakacode/bootstrap-loader/tree/master/examples, still work correctly.

Bonus points for adding an entry to the CHANGELOG.md.

**Comment by x-yuri** [comment]
> Can you add an example to https://github.com/shakacode/bootstrap-loader/tree/master/examples?

@justin808 By example you mean another directory in `examples` dir with an app, that makes use of `sass-resources-loader`? That can be built with Bootstrap 3, 4 for development or production environment?

> Also, please confirm that the all the examples, https://github.com/shakacode/bootstrap-loader/tree/master/examples, still work correctly.

By still work correctly you mean that page appearance doesn't change?

**Comment by justin808** [comment]
> Can you add an example to https://github.com/shakacode/bootstrap-loader/tree/master/examples?

> @justin808 By example you mean another directory in `examples` dir with an app, that makes use of `sass-resources-loader`? That can be built with Bootstrap 3, 4 for development or production environment?

Sounds good. Pick any example and add the sass-resources-loader.

> Also, please confirm that the all the examples, https://github.com/shakacode/bootstrap-loader/tree/master/examples, still work correctly.

By still work correctly you mean that page appearance doesn't change?

> I'll merge this once I have a small sample where I can verify this.

> If you just want to confirm, that `sass-resources-loader` doesn't work without a PR, I can provide here an archive with an app that demonstrates just that.

Doesn't crash during build or running. No console errors. Looks about the same.

**Comment by x-yuri** [comment]
@justin808 I'm not sure I understand what's the idea of adding `sass-resources-loader` example. There are 3 types of examples I could think of:

1. Example that confirms that `bootstrap-loader` works with `sass-resources-loader`. I'd made it an archive with an app attached to this page.

2. Example that shows users how to use `bootstrap-loader`. These kind of examples go to the `examples` dir.

3. Example that shows users how to use `sass-resources-loader`. `examples` dir (and this repository) doesn't seem like a good place for these. And that's what you seem to want me to do.

So let me show you the [diff][1] first.

[1]: https://github.com/shakacode/bootstrap-loader/pull/357/commits/8269d5cf572babe15b7681890f04f14a2d34c39b

**Comment by justin808** [comment]
@x-yuri see https://github.com/shakacode/bootstrap-loader/pull/362

I'm a bit confused on why you want to have the sass-resources-loader in your bootstrap config for the non-css-modules example? Maybe the bugfix is fine, but the example for **basic** doesn't make sense?

**Comment by justin808** [comment]
@x-yuri You seem to understand the issue way better than me.

> Hopefully that clarifies my take on it. But if you still want an example, I can try to modify css-modules example to make it use customization.scss, that uses variables from resource file with the help of sass-resources-loader. Or you can go ahead with your PR. Whatever works best for you.

Please go ahead and modify the example. I'll try it out and merge it, and cancel my PR.

**Comment by x-yuri** [comment]
@justin808 Okay. Hopefully that's all there is to it.

`multiple-entries` example is broken as you might know. The `README.md` is outdated, and even if I follow the steps, `npm run install-local` fails.

`yarn install` has changed the lock files, particularly (`basic` example):

```diff
 "bootstrap-loader@file:../..":
-  version "2.2.0"
+  version "3.0.1"
   dependencies:
     chalk "2.4.1"
     escape-regexp "0.0.1"
```

Not sure if that's an issue.

**Comment by justin808** [comment]
@x-yuri Hey, I really appreciate your patience here. I loaded the code and tried to see a change when I changed $custom-border-radius: 50px; to some other value in both the bs3:dev and bs4:dev setups.

Can you please provide some instructions in https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/README.md as how sass-resources-loader works. I wanted to see a change in the UI. 

You can add an image to this PR in a comment and copy the markdown from the comment into the README.md file.

Also, should this be 3.0.2 or 3.1.0? Can you please give me your desired changelog entry: https://github.com/shakacode/bootstrap-loader/blob/master/CHANGELOG.md.

image

**Comment by x-yuri** [comment]
@justin808 Bootstrap developers have a bit different idea of what alert [is][1]. You can see it at the bottom of the basic example page:

![2][]

[1]: https://getbootstrap.com/docs/3.3/components/#alerts
[2]: https://i.imgur.com/V7l8Vuk.png

Anyways, I've added the description to the [README][3] as you asked.

[3]: https://github.com/shakacode/bootstrap-loader/tree/e6a44cb1c3f3017b73da8a491c77b2afad8aad99/examples/basic#notes

Regarding the version, I think it's a bug, so `3.0.2` makes more sense to me. As for CHANGELOG entry, I'd say:

**Fixed**

* Make it work with `sass-resources-loader`

**Comment by justin808** [comment]
Released in 3.0.2.

**Pull request merged**
