### PR TITLE
Fix/upgrade examples to webpack v2

### PR DESCRIPTION
**Pull request by necronet**
Upgrade Webpack V2 in examples.
Related to. https://github.com/shakacode/bootstrap-loader/issues/274

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/282)

### CODE REVIEW

**Comment by justin808** [comment]
Did you test both basic and multipl-entries with both dev and production modes?

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/basic/package.json, line 59 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-Kefz5YKtIrLUihlFwfH:-Kefz5YKtIrLUihlFwfI:bnu7b8z) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/f5deef1cdd71b47cadb41273bdf8220022cd2c34/examples/basic/package.json#L59)):*
> ```JSON
>     "babel-preset-es2015": "^6.18.0",
>     "body-parser": "^1.15.2",
>     "bootstrap-loader": "file:///Users/jayerdis/Documents/repos/bootstrap-loader",
> ```

undo this one!

be sure to review your own diffs FIRST!

---

*[examples/css-modules/package.json, line 64 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-KefzS88cW36ope8-cjp:-KefzS88cW36ope8-cjq:b-hfpv33) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/f5deef1cdd71b47cadb41273bdf8220022cd2c34/examples/css-modules/package.json#L64)):*
> ```JSON
>     "babel-preset-es2015": "^6.18.0",
>     "babel-preset-react": "^6.16.0",
>     "bootstrap-loader": "file:///Users/jayerdis/Documents/repos/bootstrap-loader",
> ```

remove

---

*[examples/css-modules/webpack.dev.config.js, line 39 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-KefzVbHkC2oFM8amQkN:-KefzVbHkC2oFM8amQkO:b-hydvvt) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/f5deef1cdd71b47cadb41273bdf8220022cd2c34/examples/css-modules/webpack.dev.config.js#L39)):*
> ```JavaScript
>       'window.Tether': 'tether',
>       $: "jquery",
>       jQuery: "jquery"
> ```

why adding this?

do we want to remove the imports-loader: https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/webpack.dev.config.js#L60

---

*[examples/css-modules/webpack.prod.config.js, line 42 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-KefzXLX3x9Lfg0tz6sb:-KefzXLX3x9Lfg0tz6sc:b-678fi9) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/f5deef1cdd71b47cadb41273bdf8220022cd2c34/examples/css-modules/webpack.prod.config.js#L42)):*
> ```JavaScript
>       'window.Tether': 'tether',
>       $: "jquery",
>       jQuery: "jquery"
> ```

why adding this?

---

*[examples/multiple-entries/package.json, line 47 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-Keg-2_a2ntm4Oqrf9aG:-Keg-2_bLux5ShXcPL0G:b-l6mwxj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/f5deef1cdd71b47cadb41273bdf8220022cd2c34/examples/multiple-entries/package.json#L47)):*
> ```JSON
>     "babel-preset-es2015": "^6.18.0",
>     "body-parser": "^1.15.2",
>     "bootstrap-loader": "file:///Users/jayerdis/Documents/repos/bootstrap-loader",
> ```

remove

---

*[examples/multiple-entries/server.dev.js, line 36 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-Keg-5Gtgzv9PBgoROW_:-Keg-5Gtgzv9PBgoROWa:b8o8zk8) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/b1732161ef86e1b6181b9842c002dcdba85bd9e2/examples/multiple-entries/server.dev.js#L36)):*
> ```JavaScript
> 
> server.get('/',
>   (req, res) => res.redirect('/bs3'),
> ```

the linter might want the extra commas

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-:-Keg-DBLqgBYEE0ZYUdy:bffwo2)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/282#-:-KfAde4i_rw59jKrqPnv:bnfp4nl)*

**Comment by justin808** [comment]
@necronet Please confirm you verified the various npm scripts on each of the three examples and I'll merge this!

**Comment by necronet** [comment]
Yes I confirmed that the scrips worked, this is the list of commands that I test, the rest were combination of this, or just the `clean` task

```
#examples/basic
yarn start
yarn prod
yarn install-local
yarn post-install

#examples/css-modules
yarn start
yarn build
yarn prod
yarn post-install
yarn install-local

#examples/multiple-entries
yarn start
yarn build
yarn post-install
yarn install-local
```

**Comment by justin808** [comment]
@necronet Big thanks. I'll merge.

@Judahmeek @alexfedoseev Anything holding us back from changing the version number to 2.0?

**Pull request merged**
