### PR TITLE
make bootstrapPath configurable through query string

### PR DESCRIPTION
**Pull request by vjpr**
#254

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/255)

### CODE REVIEW

**Comment by justin808** [comment]
@vjpr this looks good. @alexfedoseev will have to review.

Please include in this PR the README.md and changelog entry.

Also, would this apply to the loader v1 and the upcoming v2 which supports only webpack?

@alexfedoseev I'd like to see us soon stop adding any feature/capabilities to the v1 branch.

**Comment by alexfedoseev** [comment]
> I'd like to see us soon stop adding any feature/capabilities to the v1 branch.

I don't think we should be doing anything except hotfixes for v1 as webpack v2 is released as stable.

**Comment by justin808** [comment]
@vjpr Please update to master. That might fix the CI issue! thanks to @Judahmeek!

**Comment by vjpr** [comment]
@alexfedoseev Oops, `shrinkwrap.yaml` slipped in there from pnpm. Removed.

> @justin808: Also, would this apply to the loader v1 and the upcoming v2 which supports only webpack?

It should work fine with loader v1, but its probably not worth back porting.

---

- Have modified the error message when bootstrap not found.
- Added instructions to FAQ section in `README.md`.

**Comment by justin808** [comment]
Some suggestions! Looking awesome!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXe36PMKbKp4rspvq-:-KdXe36PMKbKp4rspvq0:b7xkshj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/CHANGELOG.md#L8)):*
> ```Markdown
> ## Unreleased
> ##### Added
> - Make bootstrapPath configurable. [#255](https://github.com/shakacode/bootstrap-loader/pull/255).
> ```

` Make bootstrapPath configurable to allow XXXXX`

and  see other ones for examples. Take credit!

---

*[README.md, line 537 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXeC9HaV90O4KlIcLD:-KdXeC9HaV90O4KlIcLE:bm981fl) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/README.md#L537)):*
> ```Markdown
> ### Using a custom location for bootstrap module
> 
> By default, `bootstrap-loader` will try to resolve `bootstrap` from where `bootstrap-loader` has been installed. In [certain situations](https://github.com/shakacode/bootstrap-loader/issues/254) (e.g. npm linking, using a custom package installer) it may not be resolvable. In this case, you can pass in the location manually.
> ```

Please update https://github.com/shakacode/bootstrap-loader/blob/master/CONTRIBUTING.md with regards to how we can use link.

Also, any need to update the examples?

CC: @judahmeek 

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 25 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXea9xMBCD3ERWr-9H:-KdXea9xMBCD3ERWr-9I:b-xfs8sz) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/node_package/tests/utils/buildExtractStylesLoader.test.js#L25)):*
> ```JavaScript
>     path.join(
>       // eslint-disable-next-line prefer-template
>       fs.realpathSync(path.join(__dirname, '../../../node_modules/extract-text-webpack-plugin')) +
> ```

see a few lines up to avoid the eslint disable

---

*[src/bootstrap.loader.js, line 58 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXfBV6WbGQEGCS3AxJ:-KdXfBV6WbGQEGCS3AxK:b-3jyv53) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L58)):*
> ```JavaScript
>   if (this.cacheable) this.cacheable();
> 
>   const { extractStyles, configFilePath, bootstrapPath } = loaderUtils.parseQuery(this.query);
> ```

should we allow passing `bootstrapVersion`?

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-KdXelgbWxMJw7BJCswT:bjgo634) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
> ```JavaScript
>   logger.debug('Query from webpack config:', this.query || '*none*');
> 
>   const bootstrapVersion = config.bootstrapVersion || 4;
> ```

@vjpr @alexfedoseev @judahmeek This is potentially a big change. Why is this needed?

I'm not a fan of changing the default to v4 until: https://v4-alpha.getbootstrap.com/ changes from alpha to released. Thoughts?

How about allowing the bootstrap version in the query? or reading it from the directory we get from the bootstrap path?

---

*[src/bootstrap.loader.js, line 113 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXedw0Zga4pMZ8eE4Z:-KdXedw0Zga4pMZ8eE4_:b-roxrcy) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L113)):*
> ```JavaScript
>   logger.debug(`Bootstrap module location (abs): ${config.bootstrapPath}`);
>   if (!config.bootstrapPath) {
>     /* eslint-disable quotes */
> ```

see tests for how to work around this string thing...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-:-KdXfG06yCZC9tUq871Z:b1twt0i)*

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bootstrap.loader.js, line 58 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXfBV6WbGQEGCS3AxJ:-KdZ_CqiuganIbMq7i0s:b-qbk9eg) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L58)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

should we allow passing `bootstrapVersion`?
</blockquote></details>

We have `bootstrapVersion` setting in config from the very beginning.

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-KdZ_NWGcWe7Y01uNcpc:b-e8flzr) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

@vjpr @alexfedoseev @judahmeek This is potentially a big change. Why is this needed?

I'm not a fan of changing the default to v4 until: https://v4-alpha.getbootstrap.com/ changes from alpha to released. Thoughts?

How about allowing the bootstrap version in the query? or reading it from the directory we get from the bootstrap path?
</blockquote></details>

We already have default version set: https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.config.js#L13

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-KdZcOsprx91iwgiAPsc:bwapsrt) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary><blockquote>

We already have default version set: https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.config.js#L13
</blockquote></details>

So the `|| 4`  should be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-KdZjjUGmsKCHFwnMnXB:b-tjogn6) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

So the `|| 4`  should be removed?
</blockquote></details>

Yes, or `DEFAULT_VERSION` should be used instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-KdibrnYlAEIsAOUYyZ9:b98u9x5) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary><blockquote>

Yes, or `DEFAULT_VERSION` should be used instead.
</blockquote></details>

@vjpr Can you please make this change and we can get this merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
@vjpr We're waiting on a tiny change from you so we can merge this and create a release.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-:-Kdic09mogA0p_oB9GYr:bfcxski)*

**Comment by vjpr** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXe36PMKbKp4rspvq-:-Kdk1YlqnHbKYpdHYFy3:b-896fix) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/CHANGELOG.md#L8)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

` Make bootstrapPath configurable to allow XXXXX`

and  see other ones for examples. Take credit!
</blockquote></details>

Done.

---

*[README.md, line 537 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXeC9HaV90O4KlIcLD:-Kdk56LWvljWJ9SqcDS3:b-aadoo6) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/README.md#L537)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Please update https://github.com/shakacode/bootstrap-loader/blob/master/CONTRIBUTING.md with regards to how we can use link.

Also, any need to update the examples?

CC: @judahmeek 
</blockquote></details>

I would leave the testing setup as it is for now. This PR doesn't break it, and its for a different use case than testing with local examples.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 25 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXea9xMBCD3ERWr-9H:-Kdk6Eql_HlQYCkeUDwH:be26gqr) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/node_package/tests/utils/buildExtractStylesLoader.test.js#L25)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

see a few lines up to avoid the eslint disable
</blockquote></details>

Why should we prefer template? `path.join` makes more sense as it will handle the slashes correctly, and it will work cross platform I think.

---

*[src/bootstrap.loader.js, line 58 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXfBV6WbGQEGCS3AxJ:-Kdk6XP8NtxSOJkPupyM:b5e6pgy) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L58)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary><blockquote>

We have `bootstrapVersion` setting in config from the very beginning.
</blockquote></details>

But if you wanted to pass it in as a query param. I think it is a good idea for another PR.

---

*[src/bootstrap.loader.js, line 101 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXelgbWxMJw7BJCswS:-Kdk6rjWYw7DU-LdjZ40:b8de66a) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L101)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

@vjpr Can you please make this change and we can get this merged.
</blockquote></details>

DEFAULT_VERSION is not available in `bootstrap.loader.js`. It looks like its set in `bootstrap.config.js` so I will just remove it. I think it was accidentally added.

---

*[src/bootstrap.loader.js, line 113 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXedw0Zga4pMZ8eE4Z:-Kdk7P2FKcCiwejeS_Bc:bb37sg7) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L113)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

see tests for how to work around this string thing...
</blockquote></details>

Just seemed less clean to escape single quotes which seem standard for quoting terms within strings. I will add the escapes though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
:lgtm: BUT please revise to work within our linter guidelines.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 25 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXea9xMBCD3ERWr-9H:-KdlXXHpricqFJ9RG_2V:bxlkb2g) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/node_package/tests/utils/buildExtractStylesLoader.test.js#L25)):*
<details><summary><i>Previously, vjpr (Vaughan Rouesnel) wrote…</i></summary><blockquote>

Why should we prefer template? `path.join` makes more sense as it will handle the slashes correctly, and it will work cross platform I think.
</blockquote></details>

@vjpr it's not about path.join. It's about doing string concatenation with a `+` when you could use an ES6 template. See the first test in this file.

---

*[src/bootstrap.loader.js, line 58 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXfBV6WbGQEGCS3AxJ:-KdlXpkcRGjnLUAUsCJd:b-asu2kj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L58)):*
<details><summary><i>Previously, vjpr (Vaughan Rouesnel) wrote…</i></summary><blockquote>

But if you wanted to pass it in as a query param. I think it is a good idea for another PR.
</blockquote></details>

I'm curious if the bootstrapPath can be in the configFile? Maybe the idea is that you don't need a config file?

If you did pass in the bootstrapPath, then we should be checking the bootstrap version within that path.

---

*[src/bootstrap.loader.js, line 118 at r5](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdlYYBoC7bqXKHx3Etl:-KdlYYBpj7poKekWDFIE:b-gqj7g4) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/83b033cd66d7cef5d33a5bdbb4753f85f3ba9fa9/src/bootstrap.loader.js#L118)):*
> ```JavaScript
>     msg += 'See https://github.com/shakacode/bootstrap-loader/blob/master/README.md#usage.';
>     throw new Error(msg);
>     /* eslint-enable quotes */
> ```

Please use the ES6 template format for this string and remove the eslint-enable quotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-:-KdlYmmifKs-CY6EAVDS:b-enkw5i)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/bootstrap.loader.js, line 113 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXedw0Zga4pMZ8eE4Z:-KdlZ4afgx6LT1cJR5nU:b-kjtfhq) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L113)):*
<details><summary><i>Previously, vjpr (Vaughan Rouesnel) wrote…</i></summary><blockquote>

Just seemed less clean to escape single quotes which seem standard for quoting terms within strings. I will add the escapes though.
</blockquote></details>

Please update for the linter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by vjpr** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 25 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXea9xMBCD3ERWr-9H:-KdoaOZlaRWVPrfZcZEB:b-896fix) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/node_package/tests/utils/buildExtractStylesLoader.test.js#L25)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

@vjpr it's not about path.join. It's about doing string concatenation with a `+` when you could use an ES6 template. See the first test in this file.
</blockquote></details>

Done.

---

*[src/bootstrap.loader.js, line 58 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXfBV6WbGQEGCS3AxJ:-Kdoc1xhj0JFyQh4jXIG:b-x1t5k2) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L58)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I'm curious if the bootstrapPath can be in the configFile? Maybe the idea is that you don't need a config file?

If you did pass in the bootstrapPath, then we should be checking the bootstrap version within that path.
</blockquote></details>

So for me, the bootstrap path needs to be set dynamically at build time depending on whether bootstrap-loader is npm linked or not, and depending on which package installer I am using.

So for this use case, having it inside the config file would be useless.

You you are right, if the bootstrapPath is being set, it would be great to check the version of the package automatically.

---

*[src/bootstrap.loader.js, line 113 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdXedw0Zga4pMZ8eE4Z:-Kdob4gm508u-yXcMS6H:b-896fix) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/967f933ccc1e7c7c72d3e361e34a65388940705e/src/bootstrap.loader.js#L113)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Please update for the linter.
</blockquote></details>

Done.

---

*[src/bootstrap.loader.js, line 118 at r5](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdlYYBoC7bqXKHx3Etl:-KdobE6EJJA3fXVSYdaz:byqab9k) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/83b033cd66d7cef5d33a5bdbb4753f85f3ba9fa9/src/bootstrap.loader.js#L118)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Please use the ES6 template format for this string and remove the eslint-enable quotes.
</blockquote></details>

Oops, accidentally left that in there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
one question...

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 16 at r6](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-Kdoi_Yf2NxLG01Wl0SU:-Kdoi_Yf2NxLG01Wl0SV:b2m58qt) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d581fd2b523a26abf92ba0f809b55f0dd9a32153/node_package/tests/utils/buildExtractStylesLoader.test.js#L16)):*
> ```JavaScript
> test('buildExtractStylesLoader runs as expected', (assert) => {
>   assert.equals(buildExtractStylesLoader(['style-loader', 'url-loader', 'css-loader']),
>     path.join(
> ```

if there is only one parameter, why do we use path.join?

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 21 at r6](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdoiUk7JmNUoPPitt5p:-KdoiUk7JmNUoPPitt5q:b2m58qt) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d581fd2b523a26abf92ba0f809b55f0dd9a32153/node_package/tests/utils/buildExtractStylesLoader.test.js#L21)):*
> ```JavaScript
>   );
>   assert.equals(buildExtractStylesLoader(['isomorphic-style-loader', 'url-loader', 'css-loader']),
>     path.join(
> ```

if there is only one parameter, why do we use path.join?

---

*[src/bootstrap.loader.js, line 118 at r5](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdlYYBoC7bqXKHx3Etl:-KdoipNm_U-Wat84ptaV:b-6p4ezf) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/83b033cd66d7cef5d33a5bdbb4753f85f3ba9fa9/src/bootstrap.loader.js#L118)):*
<details><summary><i>Previously, vjpr (Vaughan Rouesnel) wrote…</i></summary><blockquote>

Oops, accidentally left that in there.
</blockquote></details>

please change this msg to be a const and use the ES6 template syntax. You won't need to escape the single quotes since you're wrapping in back ticks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-:-KdoiaKoBezZ0wlXoS0t:b-ncgv4n)*

**Comment by vjpr** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 16 at r6](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-Kdoi_Yf2NxLG01Wl0SU:-KdopxuKQAv3JhfChKd0:b-834n6i) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d581fd2b523a26abf92ba0f809b55f0dd9a32153/node_package/tests/utils/buildExtractStylesLoader.test.js#L16)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

if there is only one parameter, why do we use path.join?
</blockquote></details>

Oops.

---

*[src/bootstrap.loader.js, line 118 at r5](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdlYYBoC7bqXKHx3Etl:-KdopdB8Hj7GB4byiB8k:b-896fix) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/83b033cd66d7cef5d33a5bdbb4753f85f3ba9fa9/src/bootstrap.loader.js#L118)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

please change this msg to be a const and use the ES6 template syntax. You won't need to escape the single quotes since you're wrapping in back ticks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by vjpr** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 21 at r6](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-KdoiUk7JmNUoPPitt5p:-Kdoq4T6DQDUtgKFYQzh:b-896fix) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d581fd2b523a26abf92ba0f809b55f0dd9a32153/node_package/tests/utils/buildExtractStylesLoader.test.js#L21)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

if there is only one parameter, why do we use path.join?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255)*

**Comment by justin808** [comment]
@vjpr :lgtm_strong: 

But we need to rebase this on top of master. Let me know if you can do that.

Also, I'm guessing we don't need this for the v1 branch.

@judahmeek @alexfedoseev Can we release 2.0.0 with this change?

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/255#-:-Kdqs01MWIRjIh1znKC5:b-oh3nv5)*

**Comment by justin808** [comment]
@vjpr Please let me know when you've resolved the conflict.

**Comment by justin808** [comment]
See 2857d2b5624bc27af06bd45a64271312eadc2f5b

**Comment by justin808** [comment]
Merged

**Comment by justin808** [comment]
2.0.0-beta.22

**Comment by justin808** [comment]
@vjpr Please test this out ASAP in case there are issues! I had to resolve some merge conflicts.

**Pull request closed without merging**
