### PR TITLE
Merge pr 194 into master

### PR DESCRIPTION
**Pull request by navarroaxel**
fixed lint issues

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/198)

### CODE REVIEW

**Comment by navarroaxel** [comment]
Hi @Judahmeek and @justin808, I have fixed the issues and the tests are working.

**Comment by justin808** [comment]
:lgtm: Nice job. @judahmeek can you confirm the examples work and I'll push out the release.

---

Reviewed 2 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/198#-:-KVsdCbNzhTZgSKIw5kt:bwtbt04)*

**Comment by Judahmeek** [comment]
Unfortunately, the `multiple-entries` example doesn't work at the moment.

There's three different issues, although each one is small.

1. The multiple-entries' `server.dev.js` & `server.prod.js` files should match the other examples files with the use of IP and PORT environment variables.

2. @navarroaxel updated of webpack to `2.1.0-beta.25` broke his webpack configs. The fixes are relatively simple though and he can use the other configs as examples (extract-text-webpack-plugin's single argument and configuration has an unknown property 'postcss' were the errors I encountered and fixed).

3. The HTML of multiple-entries requests `bs3.css` & `bs4.css`, but webpack creates `app.css` so neither example page has the CSS that it should.

context: https://ide.c9.io/judahmeek/navarroaxel

**Comment by Judahmeek** [comment]
@justin808 that should do it.

**Comment by justin808** [comment]
Thanks @navarroaxel  and @Judahmeek !!!

**Comment by justin808** [comment]
I just released 2.0.0-beta.13.

**Comment by justin808** [comment]
@Judahmeek @navarroaxel It seems that what we have on master is missing a lot of what's in https://github.com/shakacode/bootstrap-loader/pull/195/files. What should we do about that?

**Pull request merged**
