### PR TITLE
removed relative bootstrap-loader paths from example package.json files

### PR DESCRIPTION
**Pull request by drlogout**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/46)

### CODE REVIEW

**Comment by justin808** [comment]
@alexfedoseev I'm not sure about this one, as we use this for testing, so we need the relative path.

**Comment by alexfedoseev** [comment]
@justin808 @drlogout I guess it's ok. Anyway I need to update it everytime before publishing b/c npm changes it to absolute path, so it's not a problem for development to have version number from npm, I'll just do `npm install ../../` before work on something. Also thus the examples will be working for everyone. So my :+1: for merging this.

**Comment by justin808** [comment]
@alexfedoseev Go ahead and merge and update the release if you feel appropriate.

**Comment by justin808** [comment]
Thanks @drlogout.

**Pull request merged**
