### PR TITLE
Document disabling jQuery in README

### PR DESCRIPTION
**Pull request by LukasBombach**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/67)

### CODE REVIEW

**Comment by LukasBombach** [comment]
Ah, it should probably say

> To avoid having to include `jQuery` in your project you can disable all scripts *in the options*

**Comment by justin808** [comment]
LGTM, but please squash to one commit and then I'll mere.

**Comment by justin808** [comment]
@LukasBombach Any word on this one? I'd like to merge it.

**Comment by LukasBombach** [comment]
@justin808 Sorry, very busy. I will do this later today.

**Comment by justin808** [comment]
@LukasBombach Keep me posted.

**Comment by justin808** [comment]
@LukasBombach if this is correct, please squash to one commit and I'll merge.

**Comment by justin808** [comment]
@LukasBombach please squash and I'll merge. Or else just copy to a new PR. If you just edit the file in place on github, it will create a new PR for you.

**Comment by LukasBombach** [comment]
Sorry for my absence. I was just gonna finish this, but I see you have already updated your readme. I'm just going to close this one.

**Pull request closed without merging**
