### PR TITLE
Minimal changes necessary for Webpack 5 compatibility

### PR DESCRIPTION
**Pull request by Judahmeek**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/399)

### CODE REVIEW

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/399)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[src/bootstrap.styles.loader.js, line 54 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/399#-MslWA8M6MXB-20vYQH2:-MslWA8M6MXB-20vYQH3:bcglzso) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/bootstrap.styles.loader.js#L54)):*
> ```JavaScript
>   }
> 
>   const bootstrapStyles = processModules(styles, bootstrapVersion, bootstrapRelPath);
> ```

I'm not exactly sure why the relative path was no longer correct, but my guess is that it's due to a change to how the Webpack context works.

Using module resolution works fine, so I'm not sure why we even had relative pathing set up in the first place.
___
*[src/utils/processStyleLoaders.js, line 68 at r1](https://reviewable.io/reviews/shakacode/bootstrap-loader/399#-MslVkeCDrYCaWxyWm8c:-MslVkeCDrYCaWxyWm8d:b-tfhbew) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a7b6a0d5d45005ff79e2cc4121cc2492c10a6b59/src/utils/processStyleLoaders.js#L68)):*
> ```JavaScript
>     loadersWithSuffix[sassLoaderIndex] = sassLoaderWithSourceMap;
>   }
> ```

Webpack 5 doesn't allow special query parameters & since sass-loader will already create sourceMaps based on the devtool settings that Webpacker uses for dev & prod environments, the simplest solution was just to remove all this.

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/399)* status: 2 of 26 files reviewed, 3 unresolved discussions (waiting on @Judahmeek and @justin808)

___
*[lib/bootstrap.config.js, line 1 at r2](https://reviewable.io/reviews/shakacode/bootstrap-loader/399#-Msm0uQz4uU4iCmPiVaM:-Msm0uQz4uU4iCmPiVaN:b-vknlmd) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/37a261f7f8337d4d6df825ec53cd3989eb061359/lib/bootstrap.config.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

Stopping review here. We've got compiled files in the PR, @judahmeek

**Review by Judahmeek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/399)* status: 2 of 26 files reviewed, 3 unresolved discussions (waiting on @justin808)

___
*[lib/bootstrap.config.js, line 1 at r2](https://reviewable.io/reviews/shakacode/bootstrap-loader/399#-Msm0uQz4uU4iCmPiVaM:-Msm1srk22iOutCApnPA:bjbf4jx) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/37a261f7f8337d4d6df825ec53cd3989eb061359/lib/bootstrap.config.js#L1)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Stopping review here. We've got compiled files in the PR, @judahmeek 
</blockquote></details>

Yeah, because I couldn't test the node package on HiChee or the tutorial otherwise.

**Review by justin808 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/399)* status: all files reviewed, 3 unresolved discussions

**Pull request closed without merging**
