### PR TITLE
Allow using with node-style-loader

### PR DESCRIPTION
**Pull request by rcalabro**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/332)

### CODE REVIEW

**Comment by justin808** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 41 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/332#-KzXEyuIzjZQzJe6FORu:-KzXEyuIzjZQzJe6FORv:b-3rx3v9) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/9709d1954962aaa6cd046d26e801a60f607d1d12/package.json#L41)):*
> ```JSON
>     "extract-text-webpack-plugin": ">=2.1.0",
>     "node-sass": "*",
>     "node-style-loader": "*",
> ```

@rcalabro What if somebody doesn't want to use the node-style-loader? Is it going to work to have this bee a peer dependency?

---

*[src/utils/buildExtractStylesLoader.js, line 13 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/332#-KzXF7xSukuUcrS7P3_b:-KzXF7xSukuUcrS7P3_c:b-7aaqp2) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/9709d1954962aaa6cd046d26e801a60f607d1d12/src/utils/buildExtractStylesLoader.js#L13)):*
> ```JavaScript
>     fallbackLoader = 'style-loader';
>   } else if (loaders[0].startsWith('isomorphic-style')) {
>     fallbackLoader = 'isomorphic-style-loader';
> ```

@rcalabro Notice that isomorphic-style-loader is not in the package.json.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/332)*

**Comment by justin808** [comment]
Thank you!

We need:

1. Changelog entry
2. REAMD.md explanation
3. examples added to the https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic directory (or similar)

and see my comments

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/332#-:-KzXFEaFgSWd2ydK6ffZ:bqx9z33)*

**Comment by justin808** [comment]
@rcalabro Any word on this one?

**Comment by justin808** [comment]
@rcalabro is this still useful?

**Comment by rcalabro** [comment]
Hi Justin
I don`t think so.... not for me at least  =)

Thanks!

**Pull request closed without merging**
