### PR TITLE
Merge pr 194 into master

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/195)

### CODE REVIEW

**Comment by justin808** [comment]
@navarroaxel We cannot merge your change into master.

Please sync up and try it out. Both production and dev versions of your examples crash on startup.

CC: @Judahmeek

**Comment by justin808** [comment]
Relates to #194 and #193.

**Comment by navarroaxel** [comment]
@justin808 I will try.

**Comment by Judahmeek** [comment]
Here's my crack at fixing the issues: https://github.com/judahmeek/bootstrap-loader/tree/merge-pr-194-into-master I didn't actually check the resulting webpages, but I got webpack to run without crashing or producing config errors.

**Comment by justin808** [comment]
@Judahmeek and @navarroaxel Please collaborate!

**Comment by Judahmeek** [comment]
The reason that Travis is currently failing is because webpack just got a `beta.26` version, which is outside the acceptable Peer Dependency set in our `package.json`, but the our current `.travis.yml` commands just attempts to install the latest beta version, which fails.

https://github.com/shakacode/bootstrap-loader/blob/merge-pr-194-into-master/.travis.yml#L10 needs to match https://github.com/shakacode/bootstrap-loader/blob/merge-pr-194-into-master/package.json#L44

**Comment by justin808** [comment]
Reviewed 21 of 28 files at r1, 4 of 9 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/195)*

**Pull request merged**
