### PR TITLE
Custom boostraprc location

### PR DESCRIPTION
**Pull request by justin808**
Option to run multiple variations of the .bootstraprc file against the same project. This fork lets developers pass in the location of their .bootstraprc file and cleans up some of the inter-dependencies between bootstrap.loader.js and bootstrap.config.js around creation of the config object.

Addresses #75.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/114)

### CODE REVIEW

**Comment by justin808** [comment]
@pherris @vpanjganj Please make comments in reviewable. I'd like to get this one closed up ASAP. Please test in the scripts per my suggestions in the CONTRIBUTING.md file.

**Comment by justin808** [comment]
I've published 1.1.0-beta.1. I'm awaiting review comments and somebody to verify that the new build works.

**Comment by alexfedoseev** [comment]
:lgtm: One comment.

I'll try beta on fng and, if it works w/o issues, let's merge.

---

Reviewed 6 of 13 files at r1, 13 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/basic/package.json, line 57 \[r3\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114#-KO3tDXIPO0WKVCWuBOX:-KO3tDXIPO0WKVCWuBOY:-1591262745) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/73ca0c3ae97eb876f96331b7657ea4029ad60441/examples/basic/package.json#L57)):*
> ```JSON
>     "babel-preset-es2015": "^6.1.18",
>     "body-parser": "^1.14.1",
>     "bootstrap-loader": "file:///Users/justin/shakacode/webpack/bootstrap-loader",
> ```

:warning: Local path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114#-:-KO3xJhLeeZJMxY2OKZP:-597044768)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/basic/package.json, line 57 \[r3\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114#-KO3tDXIPO0WKVCWuBOX:-KO3xg3KfQ81vZuz7M-l:-1285535657) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/73ca0c3ae97eb876f96331b7657ea4029ad60441/examples/basic/package.json#L57)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary>
> :warning: Local path.
</details>
Arghhh...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114)*

**Comment by justin808** [comment]
Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/basic/package.json, line 57 \[r3\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114#-KO3tDXIPO0WKVCWuBOX:-KO3yBFAbgpGG0NxHKcZ:-498453137) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/73ca0c3ae97eb876f96331b7657ea4029ad60441/examples/basic/package.json#L57)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Arghhh...
</details>
FIXED

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114)*

**Comment by justin808** [comment]
OK!

---

Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114#-:-KO3yE2wobKdnRaSG3UH:160383648)*

**Comment by alexfedoseev** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/114)*

**Pull request merged**
