### PR TITLE
Fixing resolve issue with bootstrap-sass #342

### PR DESCRIPTION
**Pull request by andrei1489**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/343)

### CODE REVIEW

**Comment by ttma1046** [comment]
I don't think a hardcode version of resolve can be treated as a fix.

**Comment by andrei1489** [comment]
@ttma1046 I added this just to keep it working while the project is updated to use resolve@1.7.0. Having the latest version of something is not necessarily a good practice, as issues like the one we are facing can happen. It really sucked having my pipeline break because of an external dependency.

**Comment by justin808** [comment]
@alexfedoseev Any opinion on this one? What if resolve 1.8.0 fixes this issue and we're pinned to 1.6.0?

**Comment by ttma1046** [comment]
@andrei1489 

Since the resolve@1.7.0 changed the return result of the `sync()` function.
The proper fix of this issue is suppose to be changing `resolveModule.js` in bootstrap-loader to handle the new return result from resolve.sync().

**Comment by andrei1489** [comment]
@ttma1046 I agree. This fix was intended to keep projects from breaking while the proper fix is being worked on. For my project I had to add resolve as a depencendy to make it work, just as you did.

**Comment by ljharb** [comment]
v1.7.1 will fix this issue soon.

**Comment by justin808** [comment]
@ljharb @andrei1489 @ttma1046 should we close this PR?

**Comment by andrei1489** [comment]
Hi @justin808 , since resolve 1.7.1 came out, I will close it.

**Pull request closed without merging**
