### PR TITLE
allow styleLoaders config with only environment

### PR DESCRIPTION
**Pull request by bertho-zero**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/227)

### CODE REVIEW

**Comment by justin808** [comment]
Any idea on the Travis failures: https://travis-ci.org/shakacode/bootstrap-loader/builds/184384238

**Comment by bertho-zero** [comment]
Yes, it's this commit: https://github.com/shakacode/style-guide-javascript/commit/03a7e826fc98535c28cc406974535312b4380904

**Comment by bertho-zero** [comment]
The package on npm is not up to date, it is not built.
I have to use my built fork in the meantime (https://github.com/bertho-zero/bootstrap-loader/tree/patch-2-build), otherwise it breaks my travis.

Please build and release.

**Comment by justin808** [comment]
Should be in  '2.0.0-beta.18': '2016-12-18T00:05:46.222Z' and '1.3.3': '2016-12-18T00:14:40.872Z' 

Can you help me debug why you're not seeing this?

**Comment by bertho-zero** [comment]
With version '2.0.0-beta.18 I have https://travis-ci.org/bertho-zero/react-redux-universal-hot-example/jobs/189976996#L525.

But with my fork built I have no error.. I do not know why...

**Pull request merged**
