### PR TITLE
Update docs with multiple CSS themes instructions

### PR DESCRIPTION
**Pull request by velveret**
This PR adds docs to address #305

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/310)

### CODE REVIEW

**Comment by justin808** [comment]
@velveret Any chance that you can provide a working example of this in the examples directory. Otherwise, we might break this doc addition going forward.

**Comment by velveret** [comment]
The existing `multiple-entries` example already has the described configuration.

**Comment by justin808** [comment]
@velveret In that case, I'll merge. Thank you!

**Comment by justin808** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/310)*

**Pull request merged**
