### PR TITLE
Issue loading popover

### PR DESCRIPTION
**Pull request by Andrey-Pavlov**
https://github.com/shakacode/bootstrap-loader/issues/172

---

This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/174)

### CODE REVIEW

**Comment by Andrey-Pavlov** [comment]
Webpack:

  { test: /bootstrap[\/\\]js[\/\\]src[\/\\]/, loader: 'imports?jQuery=jquery' },

**Comment by sky-coding** [comment]
Unless I'm mistaken, this attempts to load bootstrap src, which is written in ES6 and would require a transpiler to be configured. I would drop bootstrap-loader before installing Babel.

**Comment by Judahmeek** [comment]
Is that just because of all the additional complexity, @sky-coding?

**Comment by justin808** [comment]
I need some more explanation on this change. 

Why would one want to use the src rather than the dist? debugging?

What exactly is the problem being solved?

**Comment by sky-coding** [comment]
@justin808 the reasoning is that their `dist` code no longer supports UMD, so by compiling `src` their code can be loaded modularly. I think my fix in https://github.com/shakacode/bootstrap-loader/issues/172 is the appropriate solution to this problem.

@Judahmeek compiling third-party source code during build is just generally a bad idea, especially when it is in a different language from my source code and would require its own compiler.

**Comment by justin808** [comment]
@sky-coding @Andrey-Pavlov @Judahmeek we need some agreement on the preferred solution. I'll release once the 3 of you agree, or if we get more consensus from other community participants.

**Comment by Judahmeek** [comment]
@justin808, I followed @sky-coding's advice and addressed #172 through #175. I believe that @sky-coding will agree with me that this PR is unnecessary.

@Andrey-Pavlov, would you like to make an argument for this PR or do you agree that we can close this?

**Comment by justin808** [comment]
@Judahmeek Let's get a PR for the doc change in that case! Thanks for following up!

**Comment by Andrey-Pavlov** [comment]
I agree, we can close it. Thank you, everyone! :+1:

**Comment by Judahmeek** [comment]
@justin808 #175 is the doc change PR and you've already merged it.

**Pull request closed without merging**
