### PR TITLE
Cleanup example package.json files

### PR DESCRIPTION
**Pull request by lazzrek**
Small cleanup changes to the package.json files in /examples

[Review on Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/57)

### CODE REVIEW

**Comment by justin808** [comment]
Please see my comments. Thanks so much for the help!

We should move the dependencies up to the current versions on npm.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/basic/package.json, line 41 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-KBjpJRUdJtYAPb0ze6p:-KBjpJRVf9pYTMIYBTvR:304671860) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/53e2016c36d24dad901d812f98c04b1d83e2c1a4/examples/basic/package.json#L41)):*
Why are you removing postcss? It's needed for bootstrap 4.

---

*[examples/css-modules/package.json, line 47 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-KBjpOjCadPEymLabNH2:-KBjpOjCadPEymLabNH3:-1351548369) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/53e2016c36d24dad901d812f98c04b1d83e2c1a4/examples/css-modules/package.json#L47)):*
Needed for bootstrap 4.

Nodemon is also used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-:-KBjpVX5rxUmMi3aTl50:-1472054919)*

**Comment by justin808** [comment]
@lazzrek Let me know if you'd like an invite to our private slack room. Thanks for the help!

**Comment by lazzrek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/basic/package.json, line 41 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-KBjpJRUdJtYAPb0ze6p:-KBqT41JwLphyMUcrtuZ:204921959) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/53e2016c36d24dad901d812f98c04b1d83e2c1a4/examples/basic/package.json#L41)):*
Maybe im wrong but if you install postcss-loader it also install postcss as a dependency

---

*[examples/css-modules/package.json, line 47 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-KBjpOjCadPEymLabNH2:-KBqTuPkaGNDqCyLB1N6:-1818805040) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/53e2016c36d24dad901d812f98c04b1d83e2c1a4/examples/css-modules/package.json#L47)):*
There were 2 nodemon packages listed one in devDependencies and one in dependencies

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57)*

**Comment by lazzrek** [comment]
*[examples/css-modules/package.json, line 47 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-KBjpOjCadPEymLabNH2:-KBqUo4kVLkPGP3MbYXs:1938812713) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/53e2016c36d24dad901d812f98c04b1d83e2c1a4/examples/css-modules/package.json#L47)):*
Same for postcss-loader

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57)*

**Comment by justin808** [comment]
@lazzrek Did you test this with the bootstrap 4 examples? the card columns feature did not work unless post css was there.

**Comment by lazzrek** [comment]
i installed everything via npm and started the dev server. 
The card-clolumn was working fine.

postcss was not missing as a dependency, it was just missing in the styleLoader chain.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/57#-:-KBqVoUx6Iv4D3R8kVj6:-117385903)*

**Comment by lazzrek** [comment]
@justin808: you can invite me  to your slack if you like, my email is now public on my profile

**Comment by justin808** [comment]
@lazzrek Done!

**Comment by justin808** [comment]
Thanks @lazzrek!

**Pull request merged**
