### PR TITLE
Log bootstraprc messages to stderr.

### LINKED ISSUE #120: Logging level of bootstraprc messages
I run my production build with the following command:

`NODE_ENV=production webpack --config=webpack.config.prod.js --profile --json > build.json`

With the most recent update to version 2, the build.json begins with the following line: 

`[bootstrap-loader]:  bootstrap-loader is using config file at ...`

which breaks the file as being valid json.

Changing the log level should fix the issue I think.

### PR DESCRIPTION
**Pull request by iynaix**
Fixes #120.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/121)

### CODE REVIEW

**Comment by justin808** [comment]
:lgtm:

@alexfedoseev Take a quick look and one of us should release today.

This needs to go both on a 1.1.x and 2.x release, so we need a 1.1 branch.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/bootstrap.config.js, line 78 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/121#-KOC7AX73QBx-ree6WFB:-KOC7AX8OAWtkPr7TIrl:374322301) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7e81440e5530bd828b5980f02f082ce114d6202d/src/bootstrap.config.js#L78)):*
> ```JavaScript
> 
>   if (userConfigFileExists(configFile)) {
>     logger.warn(`bootstrap-loader is using config file at ${configFile}`);
> ```

I think this is helpful. 

The problem with using the debug option is that unless one is setting the value in the ENV, we won't pick it up.

---

*[src/utils/logger.js, line 16 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/121#-KOC7KgTJ_3zBFnLTa45:-KOC7KgUlRXbo-z1qfTg:1394308477) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7e81440e5530bd828b5980f02f082ce114d6202d/src/utils/logger.js#L16)):*
LOL! @alexfedoseev 

> "petty output"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/121#-:-KOC7XKCeOnL6hEoINwF:2009873619)*

**Comment by alexfedoseev** [comment]
@iynaix @justin808 This seems wrong to me. Why do we log message "Your config is found. All good." to `stderr`? To workaround this specific use case? This doesn't seem a good reason to break semantics to me. It should be done on configuration level, eg `loglevel: silent`.

**Comment by justin808** [comment]
@alexfedoseev The only other way is to depend on the ENV value of DEBUG existing. Where else will you define the log level? We haven't yet parsed the config file. I suppose we could print the message after the config file is parsed, and maybe save the message in a local variable.

The message is definitely helpful in that when one uses npm link, it clearly shows a wrong path.

**Comment by alexfedoseev** [comment]
@justin808 Yeah, we can use env variable and add `if` right in the logger to silent everything if this env variable exists. This seems more appropriate rather then use `stderr` wrong.

**Comment by justin808** [comment]
@iynaix Please give that a try.

**Comment by justin808** [comment]
@iynaix Please let me know if you can tackle this one.

**Comment by justin808** [comment]
@iynaix Per the comments above:

1. we **only** want to silence the output if some ENV value BOOTSTRAP_QUIET is present as this message is typically very handy. 
2. Please document this flag in the README.md. 
3. We need a short description for the CHANGELOG.md


I considered suggesting:

You can add a line after the printout: "Set ENV BOOTSTRAP_QUIET=YES" to turn off this message."

But that makes all the basic messages more annoying.

CC: @alexfedoseev

**Comment by alexfedoseev** [comment]
@justin808 Actually these changes make sense to me w/ one additional change (not related to this PR tho). We should log this info in debug mode, but in common mode, when user config is found, we can not bother user w/ this message and stay silent. But in case if path to user config **is provided**, but it's **not found** — we should throw and stop everything on this point, thus webpack will show red big bada boom message, when build is done, so user must fix path to config to fix the build.

**Comment by justin808** [comment]
@alexfedoseev The main problem I've had is bootstraprc is not found or is not the expected one due to issues with paths being relative and npm link.

The changes to debug logging will show the path used, but probably only if `export DEBUG=TRUE` (any value actually, even NO).

We can't use the value in the config file at the current points in the file. However, we could save the location of the file and after parsing print the message of what file was used if debug is true. This is actually particularly useful so you know what file to edit!

**Comment by justin808** [comment]
I feel pretty strongly about logging where we're getting the value for the bootstrap loader by default unless it's `SILENCED` because we've just had too many issues with npm link resulting in yak shaving, and due to the defaulting of the file if no file is specified.

I'm OK with either using stderr (until we run into some issue), or using an ENV value, and continuing to use stdout unless the ENV value is defined.

**Comment by justin808** [comment]
I take back my prior comment as https://nodejs.org/api/console.html#console_console_warn_data states that warn is an alias for `console.error`.

Let's do as Alex states, and we'll log the output here: https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L78 (next to the we're in DEBUG mode).

In order to do this, we need to specify the actual config path used in the config object, right here: https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.config.js#L96

@iynaix Please let me know if you can try this out.

**Comment by justin808** [comment]
@iynaix Any chance that you can help us out with finishing up this one?

If not, let us know and we can try to find another contributor to help.

**Comment by AlexKVal** [comment]
@iynaix thank you for your efforts with it.
I took up the baton.
🍒

**Pull request closed without merging**
