### PR TITLE
Misc Improvements

### PR DESCRIPTION
**Pull request by Judahmeek**
These were the two modifications to production code @justin808 mentioned while reviewing #169. Wanted to make a PR for them before I forgot. This PR is incomplete. Once #169 is merged, I will add/modify unit tests for these changes.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/177)

### CODE REVIEW

**Comment by justin808** [comment]
@Judahmeek Sounds great!

**Comment by justin808** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/buildExtractStylesLoader.js, line 12 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSPceK8w7oeT_pe2oZX:-KSPceK8w7oeT_pe2oZY:b4qcrcq) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/cf76c84446cdc90f1e72251a4c9bbde0dfa21a2a/src/utils/buildExtractStylesLoader.js#L12)):*
> ```JavaScript
>     throw new Error(`
> If you want to use 'extract-text-webpack-plugin' make sure
> your 'styleLoaders' array have 'style-loader' at index 0.
> ```

this change suggests that the error message should be different

as we're not checking for `startsWith` (index 0).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by Judahmeek** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/utils/buildExtractStylesLoader.js, line 12 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSPceK8w7oeT_pe2oZX:-KSPkCrnv1yTvkbwntku:bw63w0l) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/cf76c84446cdc90f1e72251a4c9bbde0dfa21a2a/src/utils/buildExtractStylesLoader.js#L12)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this change suggests that the error message should be different
> 
> as we're not checking for `startsWith` (index 0).
</details>
Fair point.

---

*[src/utils/buildExtractStylesLoader.js, line 32 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSPjo9uO_4o0SYRT3VG:-KSPjo9uO_4o0SYRT3VH:b-fxrg6p) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/cf76c84446cdc90f1e72251a4c9bbde0dfa21a2a/src/utils/buildExtractStylesLoader.js#L32)):*
> ```JavaScript
>       .join('')
>   );
>   return ExtractTextPlugin.extract({ fallbackLoader: 'style', loader: restLoaders });
> ```

In order to properly support `isomorphic-style-loader`, this line will also have to change, won't it? Since the fallbackLoader could be `isomorphic-style` instead of `style`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by justin808** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/utils/buildExtractStylesLoader.js, line 32 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSPjo9uO_4o0SYRT3VG:-KSPr-zqFQBuFJr6c7TU:b-wae8ad) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/cf76c84446cdc90f1e72251a4c9bbde0dfa21a2a/src/utils/buildExtractStylesLoader.js#L32)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary>
> In order to properly support `isomorphic-style-loader`, this line will also have to change, won't it? Since the fallbackLoader could be `isomorphic-style` instead of `style`?
</details>
Right. We should try here: https://github.com/shakacode/react-starter-kit-with-bootstrap-loader

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by Judahmeek** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/buildExtractStylesLoader.js, line 32 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSPjo9uO_4o0SYRT3VG:-KSUrhMy3xDWjetSk8ty:b-a4sbms) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/cf76c84446cdc90f1e72251a4c9bbde0dfa21a2a/src/utils/buildExtractStylesLoader.js#L32)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Right. We should try here: https://github.com/shakacode/react-starter-kit-with-bootstrap-loader
</details>
I have yet to investigate that repo. Check latest push though. It should work regardless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by justin808** [comment]
One tiny thing.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/tests/bootstrap.config.test.js, line 7 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUtypCzYLnGYVPCcRH:-KSUtypCzYLnGYVPCcRI:bp302d6) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e69e324ae2c232b527f4066212632642131c8221/node_package/tests/bootstrap.config.test.js#L7)):*
> ```JavaScript
> import createConfig from '../../src/bootstrap.config';
> 
> test('cC throws error if config file can not be parsed', (assert) => {
> ```

change abbreviations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-:-KSUu8eWbe_vlGuvfH7a:b6plt41)*

**Comment by Judahmeek** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[node_package/tests/bootstrap.config.test.js, line 7 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUtypCzYLnGYVPCcRH:-KSUvGiNyfxBGVJYdZx5:b-7ql1td) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e69e324ae2c232b527f4066212632642131c8221/node_package/tests/bootstrap.config.test.js#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> change abbreviations
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by justin808** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/basic/server.prod.js, line 7 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvURFU1ZWPMrP0PKI:-KSUvURFU1ZWPMrP0PKJ:bpo8hsq) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L7)):*
> ```JavaScript
> const bodyParser = require('body-parser');
> 
> const PORT = 8080;
> ```

what's the motivation for this?

---

*[examples/basic/server.prod.js, line 20 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvVtfgfyuRRbKhRIW:-KSUvVtfgfyuRRbKhRIX:bb7r2f0) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L20)):*
> ```JavaScript
> ));
> 
> server.listen(PORT, '0.0.0.0', err => {
> ```

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by Judahmeek** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/basic/server.prod.js, line 7 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvURFU1ZWPMrP0PKI:-KSUwOm52iiEiRPHrtFw:bct3l7l) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> what's the motivation for this?
</details>
My bad. I've got to change IP and PORT to actually view served webpages on Cloud 9. Forgot to revert this before pushing.

---

*[examples/basic/server.prod.js, line 20 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvVtfgfyuRRbKhRIW:-KSUw6icLwI-b7uoPRsO:bct3l7l) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L20)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> why?
</details>
My bad. I've got to change IP and PORT to actually view served webpages on Cloud 9. Forgot to revert this before pushing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by justin808** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/basic/server.prod.js, line 7 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvURFU1ZWPMrP0PKI:-KSUy22mZ2yHD454ivUD:bnjgucu) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L7)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary>
> My bad. I've got to change IP and PORT to actually view served webpages on Cloud 9. Forgot to revert this before pushing.
</details>
Could we use an ENV value that would work for everybody and default to port 4000?

---

*[examples/basic/server.prod.js, line 20 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvVtfgfyuRRbKhRIW:-KSUy6BnEZZ6LSWVnHk7:b-bqgu2) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L20)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary>
> My bad. I've got to change IP and PORT to actually view served webpages on Cloud 9. Forgot to revert this before pushing.
</details>
see prior comment on ENV value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/basic/server.prod.js, line 7 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-KSUvURFU1ZWPMrP0PKI:-KSUyVqV8ZoSciDYzDfF:b-9kmp5f) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/7ad721d6b51c3ffd2178af4ccb31a90424fef5a6/examples/basic/server.prod.js#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Could we use an ENV value that would work for everybody and default to port 4000?
</details>
Yes, but that should be a separate commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by Judahmeek** [comment]
Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177)*

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/177#-:-KSrts1cbumEbL1-vhco:bnfp4nl)*

**Pull request merged**
