### PR TITLE
Unit Testing

### PR DESCRIPTION
**Pull request by Judahmeek**
Still a lot to do. I've only created unit tests for the utils so far and there's abbreviations and whatnot that will need to be removed. Still, I figure starting the conversation early can't hurt.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/169)

### CODE REVIEW

**Comment by justin808** [comment]
Great start. For a bonus, please if there's any good JavaScript code coverage measurement tool.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYGg3_TSHqBTY4-aF:-KRBYGg3_TSHqBTY4-aG:b-lwsxtt) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/buildExtractStylesLoader.test.js#L6)):*
> ```JavaScript
> test('buildExtractStylesLoader throws error if "styleLoaders" array doesn\'t have "style-loader" at index 0', (assert) => {
>     
>   assert.throws(() => {bESL(['some-loader', 'some-other-loader'])}, Error(`
> ```

I'd spell out bESL.

Plus, we need to allow for isomorphic-style-loader at index zero: https://github.com/kriasoft/isomorphic-style-loader

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYgIGLNR0kVepQq86:-KRBYgIGLNR0kVepQq87:b-z4fe2g) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/buildExtractStylesLoader.test.js#L26)):*
> ```JavaScript
> 
>   assert.equals(bESL(['style-loader', 'url-loader', 'css-loader']),
>   path.join(`${__dirname}`, '../../../node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!style!url-loader!css-loader!'));
> ```

Indentation is not right.

run `eslint --fix`

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 28 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBY_SpgVpriGVrWfhz:-KRBY_SpgVpriGVrWfi-:br0rzgx) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/buildExtractStylesLoader.test.js#L28)):*
> ```JavaScript
>   path.join(`${__dirname}`, '../../../node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!style!url-loader!css-loader!'));
>   assert.end();
> });
> ```

red means missing new line --> please configure your editor for this.

---

*[node_package/tests/utils/checkBootstrapVersion.test.js, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYrIYi9eDMvNMeShY:-KRBYrIYi9eDMvNMeShZ:b-jcsxcu) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/checkBootstrapVersion.test.js#L5)):*
> ```JavaScript
> import cBV from '../../../src/utils/checkBootstrapVersion';
> 
> test('cBV compares version parameter with package.json version data', (assert) => {
> ```

no abbreviations cBV

---

*[node_package/tests/utils/checkBootstrapVersion.test.js, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYmr5DjyK8v121Qaq:-KRBYmr5DjyK8v121Qar:b-s4sl1b) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/checkBootstrapVersion.test.js#L6)):*
> ```JavaScript
> 
> test('cBV compares version parameter with package.json version data', (assert) => {
>     let bPath = `${path.join(`${__dirname}`, '../../../')}`;
> ```

const?

---

*[node_package/tests/utils/checkBootstrapVersion.test.js, line 7 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYl5OenxBZMMmgVSx:-KRBYl5OenxBZMMmgVSy:beuyao2) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/checkBootstrapVersion.test.js#L7)):*
> ```JavaScript
> test('cBV compares version parameter with package.json version data', (assert) => {
>     let bPath = `${path.join(`${__dirname}`, '../../../')}`;
>     
> ```

spaces are the red dots

---

*[node_package/tests/utils/createUserImport.test.js, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYyxzsfST1dDnJK2W:-KRBYyxzsfST1dDnJK2X:b-2tq11c) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/createUserImport.test.js#L5)):*
> ```JavaScript
> 
> test('cUI runs as expected', (assert) =>{
>   var webpack = {
> ```

const or let

---

*[node_package/tests/utils/getFontsPath.test.js, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBZO54gSXGGDi-E8Tm:-KRBZO54gSXGGDi-E8Tn:bk80vt2) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/getFontsPath.test.js#L6)):*
> ```JavaScript
> test('gFP works as expected', (assert) =>{
>   assert.equals(gFP('../'), '../assets/fonts/bootstrap/');
> 	assert.end();
> ```

tab char

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-:-KRBZbEkWzJ4Tu6fWN3k:bfbyy4r)*

**Comment by Judahmeek** [comment]
Util tests cleaned up. Regarding code coverage, I've found tools that work with tape and I've found tools that work with babel, but I'm not sure I've seen anything guaranteed to work with both. https://www.npmjs.com/package/tape-istanbul and https://github.com/substack/covert are both possibilities.

---

Review status: 15 of 22 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-:-KRGJ6jim4F3Ujc_VICQ:bkduxra)*

**Comment by justin808** [comment]
Let me know when this is ready for merge. Looking great!

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[node_package/tests/bootstrap.config.test.js, line 9 \[r2\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRH129jUfMpfLdGSCv4:-KRH129jUfMpfLdGSCv5:bokxp9o) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e2d6c899d9fb380eee905f34ffe3382ed8324bf8/node_package/tests/bootstrap.config.test.js#L9)):*
> ```JavaScript
>                 /Config file cannot be parsed/);
> 	assert.end();
> });*/
> ```

are we planning on enabling this test?

---

*[node_package/tests/bootstrap.config.test.js, line 11 \[r2\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRH17AkOHUliqdbX48-:-KRH17AkOHUliqdbX480:bw7oong) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e2d6c899d9fb380eee905f34ffe3382ed8324bf8/node_package/tests/bootstrap.config.test.js#L11)):*
> ```JavaScript
> });*/
> 
> test('cC throws error if bootstrapVersion not found', (assert) =>{
> ```

abbreviation?

---

*[node_package/tests/bootstrap.loader.test.js, line 7 \[r2\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRH0yNqqlEV5lPPacJF:-KRH0yNqqlEV5lPPacJG:bjovvub) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e2d6c899d9fb380eee905f34ffe3382ed8324bf8/node_package/tests/bootstrap.loader.test.js#L7)):*
> ```JavaScript
>   assert.throws(() => {require('../../lib/bootstrap.loader!../../no-op.js');}, /You might want to pass the full path/);
> 	assert.end();
> });
> ```

missing new line

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYGg3_TSHqBTY4-aF:-KRH1HEP3p6Y9F9_cVxy:b-gf11tw) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/buildExtractStylesLoader.test.js#L6)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I'd spell out bESL.
> 
> Plus, we need to allow for isomorphic-style-loader at index zero: https://github.com/kriasoft/isomorphic-style-loader
</details>
Is this fixed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-:-KRH1Mk34sFiugK958x3:bq4avxg)*

**Comment by Judahmeek** [comment]
Review status: 5 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

*[node_package/tests/bootstrap.config.test.js, line 9 \[r2\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRH129jUfMpfLdGSCv4:-KRK9Ipb8vfEOArojUG0:b-w7z8vr) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e2d6c899d9fb380eee905f34ffe3382ed8324bf8/node_package/tests/bootstrap.config.test.js#L9)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> are we planning on enabling this test?
</details>
No, I'm not planning on changing any production code this commit. I was going to leave the commented out test as a reminder, but that's unnecessary so I'll remove it.

---

*[node_package/tests/utils/buildExtractStylesLoader.test.js, line 6 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRBYGg3_TSHqBTY4-aF:-KRKAlV2nrG__1WBbL5O:b-bk4p8v) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d2b827081eeb0746ce9e24843f122084b8cbc662/node_package/tests/utils/buildExtractStylesLoader.test.js#L6)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Is this fixed?
</details>
I'd rather not change any production code in this commit, but here is the specific line that will have to be modified to support `isomorphic-style-loader`.

---

*[node_package/tests/bootstrap.loader.test.js, line 7 \[r2\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KRH0yNqqlEV5lPPacJF:-KRKA67iKf_UfF-8fZoX:balqhmm) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/e2d6c899d9fb380eee905f34ffe3382ed8324bf8/node_package/tests/bootstrap.loader.test.js#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> missing new line
</details>
I'm removing this test since it'll be much easier to test `bootstrap.loader.js` through integration testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169)*

**Comment by Judahmeek** [comment]
Alright. Fixed all linting errors, rebased, and updated. Travis is still failing though due to some wierdness involving how it handles peerDependencies.

**Comment by justin808** [comment]
Once you get the Travis thing fixed, let's merge this. Great job!

---

Reviewed 1 of 17 files at r1, 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 12 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KS4wOZzpPrCDSenQ8Q7:-KS4wOZzpPrCDSenQ8Q8:b-dp36pf) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/26396fe2fbd5313b1696083f37dd3aa0a508be22/.travis.yml#L12)):*
> ```YAML
>   - npm install webpack@">=2.1.0-beta"
>   - npm install eslint-plugin-jsx-a11y@^2.1.0
>   - npm install eslint-plugin-react@^6.0.0
> ```

the non peer dependencies should go into the package.json file and shouldn't be duplicated here, or else they will get out of sync.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-:-KS4wlS6BltbYXNvOe4h:b-nkacz5)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 12 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169#-KS4wOZzpPrCDSenQ8Q7:-KS9CibAuGjrR31G3wBZ:b-t7s3v0) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/26396fe2fbd5313b1696083f37dd3aa0a508be22/.travis.yml#L12)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> the non peer dependencies should go into the package.json file and shouldn't be duplicated here, or else they will get out of sync.
</details>
Do peer dependencies of dependencies qualify as dependencies, peer dependencies, or neither? As you can see from https://travis-ci.org/shakacode/bootstrap-loader/builds/160746730, the 'eslint' plugins are PD's of eslint-config-airbnb and 'file-loader' is a PD of 'url-loader'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/169)*

**Comment by justin808** [comment]
Thanks @Judahmeek!

**Pull request merged**
