### PR TITLE
Move lint dependencies to dev dependencies.

### LINKED ISSUE #267: Should eslint-xxx be peerDependencies?
```
npm install
...
WARN registry.npmjs.org/bootstrap-loader/2.0.0-beta.21 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
WARN registry.npmjs.org/bootstrap-loader/2.0.0-beta.21 requires a peer of eslint-plugin-react@^6.6.0 but none was installed.
```

Wouldn't they just be for development - so devDependencies?

### PR DESCRIPTION
**Pull request by ruiaraujo**
Closes #267

This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/270)

### CODE REVIEW

**Comment by justin808** [comment]
LGTM

**Comment by ruiaraujo** [comment]
@justin808 Can we get a new beta with this? I use shrinkwrap and can't install bootstrap-loader until this is released.

**Comment by justin808** [comment]
give me 30 min

**Comment by justin808** [comment]
2.0.0-beta.22

Please test this out ASAP in case there are issues! I had to resolve some merge conflicts.

**Pull request merged**
