### PR TITLE
Support extract text plugin 2

### PR DESCRIPTION
**Pull request by vpanjganj**
Just FYI: 

1. I used Node 6.2.0 and npm 3.10.6. 
2. I had to change font-awsome-loader in order to make it work; it's already a pull request for it and needs revising. 
3. In the sample projects, 'bootstrap-loader' dependecies still point to my local machine which needs to be changed to beta release version after push. 
4. In sample projects' webpack settings, I changed `webpack.ProvidePlugin` parameters from doublequote to singlequote for linting. I'm not sure whether it was left like that intentionally however my change didn't break anything.
```
    new webpack.ProvidePlugin({
      'window.Tether': 'tether',
    }),
```

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/110)

### CODE REVIEW

**Comment by justin808** [comment]
A few comments.  We want to add this one after: https://github.com/shakacode/bootstrap-loader/pull/90#issuecomment-235130209

I think we could do something with the examples/basic to make them work with the old or new extract-styles and webpack.

Does anybody else feel that we should support both old and new for a bit? I feel that many projects are still on Webpack 1.x, probably for at least another 6 months.

We could bump the major version for this project and release bug fixes only for the older version.

CC: @alexfedoseev 

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[.gitignore, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDMVAs015Ba_f4xCi:-KNaDMVAs015Ba_f4xCj:838428385) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/.gitignore#L5)):*
> ```
> *.log
> .DS_Store
> **/.idea/
> ```

this should go in your global gitignore

---

*[package.json, line 43 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDQF5kTK5owGcA0-J:-KNaDQF5kTK5owGcA0-K:-289117115) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/package.json#L43)):*
> ```JSON
>     "sass-loader": "*",
>     "url-loader": "*",
>     "webpack": "^2.1.0-beta"
> ```

can we do a greater than for a peer?

---

*[README.md, line 58 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDXjivON6bY7UrlL5:-KNaDXjivON6bY7UrlL6:-486316241) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/README.md#L58)):*
> ```Markdown
> ```
> 
> Or add `bootstrap-loader` as [a module in an entry point](https://webpack.github.io/docs/configuration.html#entry) in your webpack config (you'll need Webpack 2 beta and higher):
> ```

you mean 2.1 beta?

---

*[README.md, line 157 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaD_WtyfVnMWRFn5In:-KNaD_WtyfVnMWRFn5Io:676034543) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/README.md#L157)):*
> ```Markdown
> Default: `false`
> 
> Extract styles to stand-alone css file using `extract-text-webpack-plugin` version 2.0.0-beta or higher. See [extract-text-plugin](https://github.com/webpack/extract-text-webpack-plugin) for more details.
> ```

2.1?

---

*[examples/basic/package.json, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDd7NV9kqWb8zyxED:-KNaDd7NV9kqWb8zyxEE:-78349792) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/examples/basic/package.json#L12)):*
> ```JSON
>     "start": "nodemon --watch app/markup --ext html server.dev.js",
>     "clean": "rm -rf public/",
>     "lint": "eslint --ext .js .",
> ```

:thumbsup: 

please add the eslint-config-shakacode like this:

* https://github.com/shakacode/RnNavigationExperimental/blob/master/package.json#L33

* https://github.com/shakacode/RnNavigationExperimental/blob/master/.eslintrc.json#L2

---

*[examples/basic/package.json, line 50 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaE2RqXGQjJbV60qC8:-KNaE2RrqT-_Akab4NhV:-891326514) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/examples/basic/package.json#L50)):*
> ```JSON
>     "babel-preset-es2015": "^6.1.18",
>     "body-parser": "^1.15.2",
>     "bootstrap-loader": "file:///Users/Vahid/bootstrap-loader",
> ```

this will have to change

---

*[src/utils/buildExtractStylesLoader.js, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaEXi4B0hMHJKr-sCo:-KNaEXi4B0hMHJKr-sCp:-30404245) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/src/utils/buildExtractStylesLoader.js#L31)):*
> ```JavaScript
>       .join('')
>   );
>   return ExtractTextPlugin.extract({ fallbackLoader: 'style', loader: restLoaders });
> ```

Can we have a conditional here to check for the new or old extract styles plugin?

If we can support webpack 1 and the old extract styles loader, that will be best for the community for a while.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-:-KNaEkOlfqvL4_1TrbzR:-1243553779)*

**Comment by vpanjganj** [comment]
@justin808 Pull request is updated. 

-On putting conditions to support both versions: I also thought of that but I don't think it's possible. I think we can do what extractTextPlugin is doing, for `webpack 2.1.0-beta` you should use `extraxt-text-webpack-plugin 2.1.0-beta`. And I think when final webpack 2 is out they will also have a version 2 release of ExtraxtTextPlugin as well. We can sync with them too and keep releasing this in beta and only push a main release at same time as webpack 2 and ExtractTextPlugin 2.

- I added `eslint-config-shakacode` which forced me to do loads of linting.

- I did the global gitignore bit as well as documentation changes

- This project still relies on recent changes in `font-awesome-loader` (there is a PR waiting for that)

**Comment by justin808** [comment]
Webpack has these versions:
Here are the relevant versions.

I'll make a branch v2.

So once this PR is done, we'll merge to the v2 branch and push up 2.0.0-beta.1

We'll need to update the README.md on master to reflect this availability.

`npm info webpack`
<details>
     '1.12.9': '2015-11-24T07:10:18.190Z',
     '2.0.1-beta': '2015-11-24T07:31:45.679Z',
     '2.0.2-beta': '2015-12-22T11:54:13.341Z',
     '1.12.10': '2016-01-06T19:30:18.689Z',
     '1.12.11': '2016-01-11T18:15:01.443Z',
     '2.0.3-beta': '2016-01-21T18:18:08.548Z',
     '2.0.4-beta': '2016-01-21T18:20:09.285Z',
     '1.12.12': '2016-01-23T12:50:31.115Z',
     '2.0.5-beta': '2016-01-26T17:20:53.977Z',
     '2.0.6-beta': '2016-01-30T12:24:29.216Z',
     '2.0.7-beta': '2016-02-04T13:48:02.251Z',
     '1.12.13': '2016-02-04T14:42:30.738Z',
     '2.1.0-beta.0': '2016-02-22T08:45:09.243Z',
     '2.1.0-beta.1': '2016-02-22T12:30:43.760Z',
     '2.1.0-beta.2': '2016-02-22T14:32:13.672Z',
     '1.12.14': '2016-02-22T22:05:15.190Z',
     '2.1.0-beta.3': '2016-02-22T22:07:26.237Z',
     '2.1.0-beta.4': '2016-02-24T23:09:23.255Z',
     '2.1.0-beta.5': '2016-04-10T22:46:00.897Z',
     '1.12.15': '2016-04-10T22:48:12.861Z',
     '1.13.0': '2016-04-15T13:18:35.147Z',
     '2.1.0-beta.6': '2016-04-21T23:05:28.388Z',
     '2.1.0-beta.7': '2016-05-06T22:01:04.942Z',
     '1.13.1': '2016-05-20T06:48:52.517Z',
     '2.1.0-beta.8': '2016-05-29T18:53:52.233Z',
     '2.1.0-beta.9': '2016-06-04T18:21:38.640Z',
     '2.1.0-beta.10': '2016-06-05T18:20:51.000Z',
     '2.1.0-beta.11': '2016-06-05T18:52:50.405Z',
     '2.1.0-beta.12': '2016-06-05T21:03:11.020Z',
     '2.1.0-beta.13': '2016-06-07T22:26:36.522Z',
     '2.1.0-beta.14': '2016-06-24T00:02:58.360Z',
     '2.1.0-beta.15': '2016-06-28T23:23:52.760Z',
     '2.1.0-beta.16': '2016-07-13T09:12:33.396Z',
     '2.1.0-beta.17': '2016-07-13T12:05:30.210Z',
     '2.1.0-beta.18': '2016-07-15T21:27:18.623Z',
     '2.1.0-beta.19': '2016-07-17T22:49:59.806Z',
     '2.1.0-beta.20': '2016-07-20T22:42:07.260Z' },
</details>


`  npm info extract-text-webpack-plugin`
<details>
     '1.0.1': '2016-01-06T18:27:40.799Z',
     '2.0.0-beta.0': '2016-07-13T07:28:59.647Z',
     '2.0.0-beta.1': '2016-07-13T12:04:23.150Z',
     '2.0.0-beta.2': '2016-07-15T20:17:53.559Z',
     '2.0.0-beta.3': '2016-07-20T12:46:32.640Z' },
</details>

`npm info bootstrap-loader`
<details>
     '1.0.9': '2016-02-29T10:33:27.993Z',
     '1.0.10': '2016-03-18T09:21:45.275Z' },
</details>

**Comment by justin808** [comment]
Reviewed 2 of 10 files at r1, 22 of 22 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 43 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDQF5kTK5owGcA0-J:-KNdEBdq8Hoj4k8u9Uz-:5173665) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/package.json#L43)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> can we do a greater than for a peer?
</details>
OK

---

*[README.md, line 58 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDXjivON6bY7UrlL5:-KNdE3yqjm9CVFvaKTGH:5173665) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/README.md#L58)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> you mean 2.1 beta?
</details>
OK

---

*[examples/basic/package.json, line 12 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDd7NV9kqWb8zyxED:-KNdEWRTqaNd_B86sb4-:5173665) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/examples/basic/package.json#L12)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> :thumbsup: 
> 
> please add the eslint-config-shakacode like this:
> 
> * https://github.com/shakacode/RnNavigationExperimental/blob/master/package.json#L33
> 
> * https://github.com/shakacode/RnNavigationExperimental/blob/master/.eslintrc.json#L2
> 
</details>
OK

---

*[examples/basic/package.json, line 50 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaE2RqXGQjJbV60qC8:-KNdEZoL2jD9y3V23rVf:5173665) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/examples/basic/package.json#L50)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this will have to change
</details>
OK

---

*[.gitignore, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaDMVAs015Ba_f4xCi:-KNdF70X845wSMtFSz7Z:5173665) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/.gitignore#L5)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this should go in your global gitignore
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110)*

**Comment by justin808** [comment]
:lgtm: We'll merge after #114. 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-:-KO2TEtwG0FGWcvNt2Zw:2021925349)*

**Comment by alexfedoseev** [comment]
:lgtm: Ome comment.

---

Reviewed 1 of 10 files at r1, 20 of 22 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/utils/buildExtractStylesLoader.js, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaEXi4B0hMHJKr-sCo:-KO42mc6Dgh2GXHLIdDx:-237173457) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/src/utils/buildExtractStylesLoader.js#L31)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Can we have a conditional here to check for the new or old extract styles plugin?
> 
> If we can support webpack 1 and the old extract styles loader, that will be best for the community for a while.
</details>
I looked into it and looks like the only way to check it is to resolve `package.json` of `extract-text-webpack-plugin` installed package and use its `version` property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-:-KO43U1h7knycQ91hyy1:-952917897)*

**Comment by justin808** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/utils/buildExtractStylesLoader.js, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaEXi4B0hMHJKr-sCo:-KO45jfRU2mAiSMiTK8N:713936876) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/src/utils/buildExtractStylesLoader.js#L31)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary>
> I looked into it and looks like the only way to check it is to resolve `package.json` of `extract-text-webpack-plugin` installed package and use its `version` property.
</details>
@alexfedoseev We'll use 2.x to mean 2.x webpack, extract text plugin, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-:-KO45pKSUIYTsmqYTZlW:1417088721)*

**Comment by vpanjganj** [comment]
*[src/utils/buildExtractStylesLoader.js, line 31 \[r1\]](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110#-KNaEXi4B0hMHJKr-sCo:-KO4J_QGDLFeFzWWshhb:-1189193663) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/adc7aa6720a78b87634c146cbb72c547040bc482/src/utils/buildExtractStylesLoader.js#L31)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> @alexfedoseev We'll use 2.x to mean 2.x webpack, extract text plugin, etc.
</details>
I agree with @alexfedoseev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/110)*

**Comment by justin808** [comment]
@vpanjganj Please rebase your commits down to one and apply this commit on top of master.

Otherwise, there will be too many merge commits and other noise.

**Comment by vpanjganj** [comment]
@justin808 yup I'm on it now.

**Comment by vpanjganj** [comment]
@justin808, Conflicts with the base branch are resolved now. sampleI tested the sample projects and then I set the `bootsrap-loader` version to `^2.0.0-beta` assuming that this will be our release version.

**Comment by justin808** [comment]
1. On this closed PR, we checked in a .bootstraprc. That is not necessary.
2. We need to be very clear on the README.md that it now refers to V2, and we should have a 1.1 branch with a link in the README so that it's easily available.

**Pull request merged**
