### PR TITLE
Update Example Dependencies

### PR DESCRIPTION
**Pull request by Judahmeek**
Should be good to go. `resolve-url-loader` upgraded to `^2.0.0` and examples running and linted.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/261)

### CODE REVIEW

**Comment by justin808** [comment]
yarn or npm?

---

Reviewed 1 of 13 files at r1, 22 of 22 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/css-modules/package.json, line 26 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-Kd7cMAHTi3JkJEoj2os:-Kd7cMAHTi3JkJEoj2ot:boibzgj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/1a96dada6c42b7c6f2c085df97ca09c30ba4cf8a/examples/css-modules/package.json#L26)):*
> ```JSON
>     "bs3:default:prod": "npm run bs3:default:setup && npm run prod",
>     "bs4:default:prod": "npm run bs4:default:setup && npm run prod",
>     "install-local": "rm -rf node_modules/bootstrap-loader && npm install --save-dev ../.. && npm run post-install"
> ```

are we using yarn or npm?

@judahmeek you are still using npm run here.

---

*[examples/css-modules/package.json, line 63 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-Kd7bnolDgMlq43uzZAt:-Kd7bnomKCOwoSR20dsM:b-3mhne6) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/1a96dada6c42b7c6f2c085df97ca09c30ba4cf8a/examples/css-modules/package.json#L63)):*
> ```JSON
>     "babel-preset-es2015": "^6.18.0",
>     "babel-preset-react": "^6.16.0",
>     "bootstrap-loader": "file:///Users/judahmeek/Apps/bootstrap-loader",
> ```

Can't refer to your local files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-:-Kd8NWAX43BuBlsqzJKY:b-pg16rq)*

**Comment by Judahmeek** [comment]
Both?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/css-modules/package.json, line 26 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-Kd7cMAHTi3JkJEoj2os:-Kd8OM_gjks13U0XwGrh:b-4teme8) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/1a96dada6c42b7c6f2c085df97ca09c30ba4cf8a/examples/css-modules/package.json#L26)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

are we using yarn or npm?

@judahmeek you are still using npm run here.
</blockquote></details>

I figured we could support both. I ran yarn in terminal and left the scripts as npm. I assume almost anyone who uses yarn can easily set up npm or modify our `package.json`, but not vice versa (since those with less experience generally start with npm).

---

*[examples/css-modules/package.json, line 63 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-Kd7bnolDgMlq43uzZAt:-Kd8Oymu0-5smIMRBtRG:bjylyfv) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/1a96dada6c42b7c6f2c085df97ca09c30ba4cf8a/examples/css-modules/package.json#L63)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Can't refer to your local files
</blockquote></details>

Ouch. Well, I caught 2 out of 3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-:-Kd8P2KbpnloLmFNDnZl:b-8a9w6f)*

**Comment by Judahmeek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/css-modules/package.json, line 63 at r1](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261#-Kd7bnolDgMlq43uzZAt:-Kd8Ph5LDEGSUwN0A4Q4:b-dkb5to) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/1a96dada6c42b7c6f2c085df97ca09c30ba4cf8a/examples/css-modules/package.json#L63)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Ouch. Well, I caught 2 out of 3.
</blockquote></details>

Actually, I've already fixed this. Check the latest revision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/261)*

**Comment by justin808** [comment]
@Judahmeek I think the examples should use yarn or npm. I use either, but only one within a project.

**Comment by justin808** [comment]
@Judahmeek I'll merge this. Let's put anything pending in the next PR. I'm going to cut a release! 🎉

**Comment by justin808** [comment]
2.0.0-beta.21 pushed to npm!

**Pull request merged**
