### PR TITLE
Support Webpack2 RCs

### PR DESCRIPTION
**Pull request by joewoodhouse**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/237)

### CODE REVIEW

**Comment by justin808** [comment]
Thanks @joewoodhouse!

**Comment by joewoodhouse** [comment]
Awesome - any chance you could npm publish this? I'm sort of blocked without this

**Comment by justin808** [comment]
Done. Please confirm this works. beta.19.

**Comment by joewoodhouse** [comment]
Works for me! Thanks so much for your quick response.

**Pull request merged**
