### PR TITLE
Added support Bootstrap 4 Beta

### PR DESCRIPTION
**Pull request by IvanKalinin**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/316)

### CODE REVIEW

**Comment by justin808** [comment]
Is there a good reason to even support the alpha? We'll eventually move to only support the released version.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-:-KrPZWICS1BBQf9-Piqw:b-yrmf3s)*

**Comment by IvanKalinin** [comment]
I think so.
Beta has a lot of changed. A lot of variables were renamed, so I think a lot of developers still use alpha 6. It could take a time to update their own project from alpha to beta. And we cannot break someones projects with updates

In my thoughts we can drop alpha in the next beta release

**Comment by justin808** [comment]
@ivankalinin Great work!

1. Let's remove all the beta parts. Alpha users should not upgrade.
2. Please update the CHANGELOG.md per prior entries for v2.2.0 and make any necessary changes in the README.md
3. Please confirm that you've tried all the examples in the examples directory and you've made the appropriate updates there so they are all on the beta and not the alpha.

Once the above 3 steps are done, I'll immediately create a new release for v2.2.0.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.bootstraprc-4-default, line 10 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KrXN5v8JSbDxDfESHpP:-KrXN5v8JSbDxDfESHpQ:b-l6mwxj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d30b3f55a132f8f53458ba81e1943fce86d53f43/.bootstraprc-4-default#L10)):*
> ```
> # If Bootstrap version 4-alphaX use `false`
> # If Bootstrap version 4-betaX use `true`
> isBeta: true
> ```

remove

---

*[.bootstraprc-4-default, line 63 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KrXN82gjmkQVW_w_Dik:-KrXN82gjmkQVW_w_Dil:byp18fd) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d30b3f55a132f8f53458ba81e1943fce86d53f43/.bootstraprc-4-default#L63)):*
> ```
>   # Reset and dependencies
>   # Bootstrap dropped normalize in beta
>   # Uncomment `normalize` if you still use alpha
> ```

Remove

---

*[src/bootstrap.config.js, line 130 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KrXMwcYHqDNEvtM090b:-KrXMwcYHqDNEvtM090c:b-qc1nzm) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d30b3f55a132f8f53458ba81e1943fce86d53f43/src/bootstrap.config.js#L130)):*
> ```JavaScript
>   return {
>     bootstrapVersion: parseInt(userConfig.bootstrapVersion, 10),
>     isBeta: userConfig.isBeta || false,
> ```

Do we still need this key? what purpose is it?

---

*[src/bootstrap.styles.loader.js, line 25 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KrXNFpN_An-A092WMfM:-KrXNFpN_An-A092WMfN:b-l6mwxj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d30b3f55a132f8f53458ba81e1943fce86d53f43/src/bootstrap.styles.loader.js#L25)):*
> ```JavaScript
>     bootstrapRelPath,
>     useFlexbox,
>     isBeta,
> ```

remove

---

*[src/bootstrap.styles.loader.js, line 50 at r2](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KrXND9YJJknsFxX6RQh:-KrXND9YJJknsFxX6RQi:b-53xcy0) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/d30b3f55a132f8f53458ba81e1943fce86d53f43/src/bootstrap.styles.loader.js#L50)):*
> ```JavaScript
>   }
> 
>   if (bootstrapVersion === 4 && isBeta === true) {
> ```

remove conditional for beta

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-:-KrXNGqd554stLJQDuDR:b-vjexaw)*

**Comment by IvanKalinin** [comment]
There are a bit more changes.

**Comment by justin808** [comment]
:lgtm: Just one question in the code, that probably requires a doc note.

Please confirm all examples work and I'll merge and release.

GREAT WORK!

---

Reviewed 23 of 23 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/basic/.bootstraprc-4-example, line 13 at r3](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-KripaBm1COOdS5doLA2:-KripaBm1COOdS5doLA3:bnt30nu) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/3b81d7389e68388699705a1e1d2953087c56a8ad/examples/basic/.bootstraprc-4-example#L13)):*
> ```
>   - css-loader
>   - sass-loader
>   - postcss-loader
> ```

Why did this change? Just curious. Should we document this in the CHANGELOG or README? This is pretty subtle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-:-Kripy0LlWcYM0yqZCBF:bsbxoi)*

**Comment by IvanKalinin** [comment]
Because order is matter. Postcss loader should work after sass-loader. In that order there is no errors and warnings in console.

**Comment by netbull** [comment]
@justin808 any news when the PR will merged ?

**Comment by justin808** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/316#-:-KroE_UJiaMZtLIdT5n7:bnfp4nl)*

**Comment by justin808** [comment]
Thanks @IvanKalinin!

**Comment by kuongknight** [comment]
I still found issue : Argument `$color` of `darken($color, $amount)` must be a color
When using:
bootstrap-loader: 2.2.0
bootstrap: 4.0.0-beta.3
default .bootstraprc-4-default

**Comment by justin808** [comment]
@kuongknight maybe submit a PR?

**Pull request merged**
