### PR TITLE
Allow styleLoaders to depends to env

### PR DESCRIPTION
**Pull request by bertho-zero**
```
"env": {
    "development": {
      "styleLoaders": ["style-loader", "css-loader", "resolve-url-loader", "sass-loader"],
      "extractStyles": false
    },
    "production": {
      "styleLoaders": ["style-loader", "css-loader", "sass-loader"],
      "extractStyles": true
    }
  }
```

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/222)

### CODE REVIEW

**Comment by justin808** [comment]
@bertho-zero:

1. Why this param only?
2. What's the use case?
3. Can you provide a test for this?

If we're going to do this, we'd need a readme note on this, as well as a changelog entry.

**Comment by bertho-zero** [comment]
There is already the `extractStyles` parameter, and it is the only ones, with 'styleLoaders', that can change between development and production.

My use case, this avoids having to create 2 files:
```js
"env": {
    "development": {
      "styleLoaders": ["style-loader", "css-loader", "resolve-url-loader", "sass-loader"],
      "extractStyles": false
    },
    "production": {
      "styleLoaders": ["style-loader", "css-loader", "sass-loader"],
      "extractStyles": true
    }
  }
```

I do not think there's any need for additional testing.

I updated version, change log and readme.

**Comment by justin808** [comment]
This looks good with one tiny thing.

@Judahmeek, do you concur?

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 8 at r4](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222#-KYCtVjZ12FaPQZiV1zt:-KYCtVjZ9D1hcrMQkRug:beauupu) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/a21f0786f15485148f8107a66e7afa518881cb89/CHANGELOG.md#L8)):*
> ```Markdown
> ## [2.0.0.beta.17] - 2016-12-04
> ##### Added
> - Allow `styleLoaders` to depend on the environment variable 'NODE_PATH' [#222](https://github.com/shakacode/bootstrap-loader/pull/222) by [bertho-zero](https://github.com/bertho-zero).
> ```

@bertho-zero You missed the change at the bottom of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222#-:-KYCtlrM7hAfSPGihi7_:bq5t1gj)*

**Comment by justin808** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222)*

**Comment by bertho-zero** [comment]
It is done

**Comment by Judahmeek** [comment]
Looks good to me.

**Comment by justin808** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222#-:-KYHiZNL5ppATRHSdi30:bnfp4nl)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 224 at r5](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222#-KYHj6ShDUxYjD_LZBaF:-KYHj6ShD7UP4hqcSka3:b-6hocwj) ([raw file](https://github.com/shakacode/bootstrap-loader/blob/3e4c31057523a5730352dad9c4f83ce2ab36646e/README.md#L224)):*
> ```Markdown
>   - sass-loader
> 
> # You can apply loader params here:
> ```

@bertho-zero Can you do me a favor and create 3 different fenced code blocks with a short description of each technique.

It's not appropriate to put this all in one code block as if you'd do this all in the same file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222)*

**Comment by justin808** [comment]
@bertho-zero Please update one thing in the README.md

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/222#-:-KYHjIVu0cqvNugTxl88:b2n4n0s)*

**Comment by bertho-zero** [comment]
I separated the example of other, yes it was confused.

On the other hand I do not see what examples I could add..

Not speaking very good English, I do not know what to add to the readme.

**Pull request merged**
