### PR TITLE
Make dev a bit more cross platform

### PR DESCRIPTION
**Pull request by apawsey**
Added rimraf, replaced in scripts, disabled linebreak endings in eslint,
added extra instructions to contributing.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/294)

### CODE REVIEW

**Comment by justin808** [comment]
@apawsey why use rimraf? Windows?

**Comment by apawsey** [comment]
Yeah. That was the point. Cloning this and trying to work with it on Windows is a problem.  The npm scripts don't work, and eslint complains constantly about the format of line endings.

**Comment by justin808** [comment]
@apawsey is this PR complete for all your windows issues? Can you verify this branch works on Mac OS?

**Comment by justin808** [comment]
@apawsey is this PR complete for all your windows issues? Can you verify this branch works on Mac OS?

**Comment by justin808** [comment]
@apawsey I'll reopen when you respond to my questions.

**Pull request closed without merging**
