### PR TITLE
Add option for custom $icon-font-path

### PR DESCRIPTION
**Pull request by HorizonXP**
Add configuration option to disable the addition of the default
$icon-font-path so we can use our own custom path within our Sass files.

Tested & verified with my own code. Lint passes.

Addresses option 1 of #38.

[Review on Reviewable](https://reviewable.io/reviews/shakacode/bootstrap-loader/39)

### CODE REVIEW

**Comment by justin808** [comment]
Thanks! To merge, we need:

1. Placement in the example files for bootstrap 3 & 4
2. Readme additions
3. demonstrate in /examples folder.

Thanks!

Please let me know if you have any questions, @horizonXP

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/39#-:-K9n0yK-aYs4FihVWcIJ:1723257758)*

**Comment by HorizonXP** [comment]
Just committed the requested changes.

**Comment by justin808** [comment]
@horizonXP, should we have a new  `examples/custom-icon-path` directory?

@alexfedoseev This looks overall OK.

---

Review status: 2 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/bootstrap-loader/39#-:-K9pz-GrrwJ6SiCbgrGF:-1552775467)*

**Comment by alexfedoseev** [comment]
@HorizonXP @justin808 Looks good! Going into next release. Thanks, @HorizonXP :+1:

**Pull request merged**
